all:
  hosts:
    cp1:
      ansible_host: 51.250.93.145
      ansible_user: yc-user
    node1:
      ansible_host: 51.250.89.48
      ansible_user: yc-user
    node2:
      ansible_host: 51.250.91.220
      ansible_user: yc-user
    node3:
      ansible_host: 51.250.82.4
      ansible_user: yc-user
    node4:
      ansible_host: 51.250.93.74
      ansible_user: yc-user
  children:
    kube_control_plane:
      hosts:
        cp1:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
        node4:
    etcd:
      hosts:
        cp1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
