# For change!!! Config Deployment Frontend & Backend 
# with dynamical mount NFS
# Str 28-30, 34-36, 37-40 - adding mount information!!!
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fb-app
  name: fb-pod 
  namespace: stage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fb-app
  template:
    metadata:
      labels:
        app: fb-app
    spec:
      containers:
        - image: zakharovnpa/k8s-frontend:05.07.22
          imagePullPolicy: IfNotPresent
          name: frontend
          ports:
          - containerPort: 80
          volumeMounts:                   # mount information
            - mountPath: "/static"        # mount information
              name: my-volume             # mount information
        - image: zakharovnpa/k8s-backend:05.07.22
          imagePullPolicy: IfNotPresent
          name: backend
          volumeMounts:                  # mount information
            - mountPath: "/static"       # mount information
              name: my-volume            # mount information
      volumes:                           # mount information
       - name: my-volume                 # mount information
         persistentVolumeClaim:          # mount information
           claimName: pvc                # mount information
      terminationGracePeriodSeconds: 30

---
# Config Service
apiVersion: v1
kind: Service
metadata:
  name: fb-pod
  namespace: stage
  labels:
    app: fb
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30080
  selector:
    app: fb-pod
